In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import silhouette_score
from yellowbrick.cluster import SilhouetteVisualizer
%matplotlib inline 

In [2]:
df = pd.read_csv('df_hdi_complete.csv')

In [3]:
df_country = pd.read_excel('dados_hdi.xlsx')
df_country = df_country[['Country']]

In [4]:
df = df.drop(['RHDI','Continent'], axis=1)
min_max_scaler = MinMaxScaler()
df[['HDI', 'LE', 'EYS', 'MYS', 'GNI', 'GDIV', 'GIIV', 'IHDI', 'ILE', 'IE',
       'II', 'SSP', 'TP', 'TUP', 'MA', 'CHE', 'GEE', 'PPP', 'HB', 'VE', 'RPAE',
       'WAFI', 'CDEP', 'CDE', 'FA', 'FAC', 'DMC', 'RLI', 'SLF', 'RDE']] = min_max_scaler.fit_transform(df[['HDI', 'LE', 'EYS', 'MYS', 'GNI', 'GDIV', 'GIIV', 'IHDI', 'ILE', 'IE',
       'II', 'SSP', 'TP', 'TUP', 'MA', 'CHE', 'GEE', 'PPP', 'HB', 'VE', 'RPAE',
       'WAFI', 'CDEP', 'CDE', 'FA', 'FAC', 'DMC', 'RLI', 'SLF', 'RDE']])

In [5]:
###############
### Economy ###
###############

### Defining the Economy data frame ###
df_economy = df[['HDI', 'LE', 'EYS', 'MYS', 'GNI']]

### Fiting the model ###
kmeanModel = KMeans(n_clusters=3, random_state = 42)
kmeanModel.fit(df_economy)

centroids = kmeanModel.cluster_centers_
labels = kmeanModel.labels_

print(centroids)
print(labels)

df_economy['Economy'] = pd.DataFrame(labels)
#sns.lmplot(x='EYS', y='HDI', data=df_economy, fit_reg=False, hue='Economy')
#we gonna use pca an then make a chart with te two dimenssions and user the clustering results as hue :)

[[0.90631495 0.87260318 0.68681464 0.82904866 0.37944918]
 [0.25420367 0.34281718 0.3081967  0.27397112 0.02216431]
 [0.63906338 0.66723691 0.51223352 0.62973179 0.11068308]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1]


<ipython-input-5-9407697f70e5>:18: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_economy['Economy'] = pd.DataFrame(labels)


In [6]:
##################
### Inequality ###
##################
df_inequality = df[['IHDI','ILE','IE','II','VE','RPAE','SLF']]

### Fiting the model ###
kmeanModel = KMeans(n_clusters=3, random_state = 42)
kmeanModel.fit(df_inequality)

centroids = kmeanModel.cluster_centers_
labels = kmeanModel.labels_

print(centroids)
print(labels)

df_inequality['Inequality'] = pd.DataFrame(labels)

[[0.79703847 0.08565982 0.12176636 0.18449338 0.17933066 0.99902251
  0.80808425]
 [0.18138946 0.68153586 0.71519913 0.41233414 0.74121855 0.24615779
  0.20251521]
 [0.51528143 0.29577118 0.36595513 0.37401171 0.39521402 0.92763072
  0.39334831]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 2 2 0 2 2 2 0 0 2 0 2 0 0 0 2 0 0 2 2 0 2
 2 2 0 2 2 2 0 0 2 2 2 2 2 0 2 0 2 0 2 2 2 2 2 2 0 1 2 2 2 0 1 2 2 2 2 2 0
 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 1 2 2 2 1 1 2 1
 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1]


<ipython-input-6-69419b634b62>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_inequality['Inequality'] = pd.DataFrame(labels)


In [7]:
##############
### Gender ###
##############
df_gender = df[['GDIV', 'GIIV','SSP', 'WAFI']]

### Fiting the model ###
kmeanModel = KMeans(n_clusters=4, random_state = 42)
kmeanModel.fit(df_gender)

centroids = kmeanModel.cluster_centers_
labels = kmeanModel.labels_

print(centroids)
print(labels)

df_gender['Gender'] = pd.DataFrame(labels)

[[0.87339052 0.38895191 0.24183454 0.75389918]
 [0.85969146 0.48280356 0.55512933 0.4349951 ]
 [0.89881353 0.08983794 0.5728162  0.90376744]
 [0.67785112 0.68937287 0.29046781 0.22755394]]
[2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2
 2 0 0 0 0 0 2 0 1 0 2 0 0 0 0 2 0 0 2 1 1 1 0 0 1 0 0 2 0 3 1 1 1 0 0 0 1
 1 0 0 1 1 0 1 2 1 0 2 1 1 1 1 1 3 3 0 1 0 1 0 1 0 0 0 3 1 0 0 1 1 1 1 0 0
 1 0 1 3 3 0 1 1 1 3 1 3 1 1 1 1 1 3 1 0 1 3 0 3 0 1 3 3 0 1 1 0 3 3 3 3 3
 3 1 0 3 3 3 0 3 3 3 1 1 3 3 1 3 1 3 3 1 3 3 3 3 1 3 3 3 3 3 3 3 1 3 3 3 1
 3 3 3 3]


<ipython-input-7-c0a622c9f82e>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_gender['Gender'] = pd.DataFrame(labels)


In [8]:
######################
### Population/Age ###
######################
df_population = df[['TP', 'TUP', 'MA']]

### Fiting the model ###
kmeanModel = KMeans(n_clusters=4, random_state = 42)
kmeanModel.fit(df_population)

centroids = kmeanModel.cluster_centers_
labels = kmeanModel.labels_

print(centroids)
print(labels)

df_population['Population'] = pd.DataFrame(labels)

[[0.03556559 0.25544448 0.17248889]
 [0.01818891 0.69433015 0.38696849]
 [0.02210818 0.79830069 0.8054711 ]
 [0.03930206 0.3979114  0.67843164]]
[2 3 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 1 2 3 3 2 2 2 2 2 2 2 2 1 2 3 2 3 2 2
 2 3 2 1 1 2 3 1 1 1 2 3 1 1 2 2 1 2 2 1 1 3 1 3 1 1 2 3 3 3 3 3 2 1 3 3 3
 1 3 2 3 1 3 3 3 1 1 3 1 3 3 1 3 1 1 1 1 3 1 3 1 1 1 1 1 1 0 1 1 1 1 0 0 0
 1 1 1 1 0 1 3 1 0 1 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0]


<ipython-input-8-6ccc3580cf11>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_population['Population'] = pd.DataFrame(labels)


In [9]:
#############################################
### Health/Education/Research Expenditure ###
#############################################
df_expenditure = df[['CHE','GEE','RDE']]

### Fiting the model ###
kmeanModel = KMeans(n_clusters=4, random_state = 42)
kmeanModel.fit(df_expenditure)

centroids = kmeanModel.cluster_centers_
labels = kmeanModel.labels_

print(centroids)
print(labels)

df_expenditure['Expenditure'] = pd.DataFrame(labels)

[[0.37720736 0.31980064 0.09715144]
 [0.19026941 0.23588424 0.10008329]
 [0.57538058 0.40772031 0.28766234]
 [0.59925142 0.41154048 0.6874649 ]]
[2 0 3 1 2 3 3 2 2 3 3 1 2 3 2 2 3 3 3 3 2 2 3 1 2 2 2 0 0 2 1 0 0 0 0 2 0
 2 0 0 1 1 0 0 1 0 1 0 1 2 1 1 0 1 0 0 0 0 0 1 0 0 1 1 0 0 1 0 0 2 0 1 0 1
 0 1 0 1 1 1 0 0 0 2 1 0 1 1 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 1 0 1
 0 1 0 0 1 2 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 2 0 2 1 0 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 1 0 1 1 1 1 0 1 0 1 2 0 0 1 1 0 1 0 0 1 1 1 0 0 2 1 0
 0 1 0 0]


<ipython-input-9-3dfe9cad23b3>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_expenditure['Expenditure'] = pd.DataFrame(labels)


In [10]:
####################
### Health Acess ###
####################
df_health = df[['PPP','HB']]

### Fiting the model ###
kmeanModel = KMeans(n_clusters=4, random_state = 42)
kmeanModel.fit(df_health)

centroids = kmeanModel.cluster_centers_
labels = kmeanModel.labels_

print(centroids)
print(labels)

df_health['Health'] = pd.DataFrame(labels)

[[0.25320244 0.21321868]
 [0.05061389 0.09206985]
 [0.53637927 0.28749721]
 [0.40323763 0.55731225]]
[0 0 2 0 2 3 2 2 2 2 2 0 0 3 2 0 0 3 2 3 2 0 3 0 2 3 3 0 2 2 0 2 0 2 3 2 3
 2 3 3 0 1 0 3 0 2 0 0 3 0 3 3 3 0 2 3 0 0 3 0 2 0 0 0 3 0 0 2 0 2 0 0 0 0
 0 0 3 0 1 1 2 0 0 0 0 0 1 2 0 3 0 0 1 1 2 0 0 0 3 1 1 0 1 1 0 0 1 1 1 1 1
 0 0 1 0 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1]


<ipython-input-10-3d917b6382ed>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_health['Health'] = pd.DataFrame(labels)


In [11]:
####################
### Environment ###
###################
df_environment = df[['CDEP', 'CDE', 'FA', 'FAC', 'DMC', 'RLI']]

### Fiting the model and ploting an example ###
kmeanModel = KMeans(n_clusters=4, random_state = 42)
kmeanModel.fit(df_environment)

centroids = kmeanModel.cluster_centers_
labels = kmeanModel.labels_

print(centroids)
print(labels)

df_environment['Environment'] = pd.DataFrame(labels)

[[0.10677696 0.22188229 0.69515457 0.26331147 0.1945199  0.73675194]
 [0.07737005 0.21033605 0.19509727 0.27185284 0.15078981 0.85295624]
 [0.04888792 0.20990386 0.35727706 0.25056011 0.11420954 0.53818925]
 [0.33001517 0.47626389 0.21189261 0.31966807 0.46462896 0.82326309]]
[1 1 1 1 1 1 0 3 1 1 0 3 1 1 2 3 3 0 2 0 1 0 0 3 1 1 3 1 3 1 3 1 1 1 3 1 0
 1 1 1 3 3 3 1 3 1 0 0 1 0 3 3 3 1 3 3 0 2 1 3 1 0 0 3 3 2 0 3 1 2 3 2 3 2
 2 2 3 1 0 2 1 1 2 0 3 2 1 1 2 1 1 1 2 2 1 1 0 0 3 3 2 1 1 2 1 1 0 2 2 0 0
 3 0 3 1 1 0 2 0 1 1 0 1 1 1 1 2 1 0 1 2 2 2 2 0 0 0 2 2 2 2 1 1 2 0 0 2 1
 0 2 0 3 2 1 0 2 1 1 2 1 1 1 2 2 1 1 1 1 1 2 1 1 1 2 0 0 1 1 1 1 2 1 1 1 1
 1 1 1 1]


<ipython-input-11-9a0b1a383488>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_environment['Environment'] = pd.DataFrame(labels)


In [12]:
############################
### Final Results so far AGAIS ###
############################
df_full_hdi = pd.concat([df_country,df_economy['Economy'],df_inequality['Inequality'],df_gender['Gender'],df_population['Population'],df_expenditure['Expenditure'],df_health['Health'],df_environment['Environment']], axis=1)

df_full_hdi.set_index('Country',inplace=True)
df_full_hdi.head()

Economy  Inequality  Gender  Population  Expenditure  \
Country                                                                        
Norway                        0           0       2           2            2   
Ireland                       0           0       2           3            0   
Switzerland                   0           0       2           2            3   
Hong Kong, China (SAR)        0           0       0           2            1   
Iceland                       0           0       2           2            2   

                        Health  Environment  
Country                                      
Norway                       0            1  
Ireland                      0            1  
Switzerland                  2            1  
Hong Kong, China (SAR)       0            1  
Iceland                      2            1

In [13]:
#####################################################################33
### pd.DataFrame(df_full).to_csv("cluster_results_hdi.csv", index=False) ### to compare ###

pd.DataFrame(df_full_hdi).to_csv("teste_cluster_results_hdi.csv", index=False)

#################################################################

In [21]:
df_full_hdi.loc['Brazil'][:]

Economy        2
Inequality     2
Gender         0
Population     1
Expenditure    2
Health         0
Environment    0
Name: Brazil, dtype: int32

In [15]:
list(df_full_hdi[df_full_hdi['Economy']==2].index.values)

['Montenegro',
 'Romania',
 'Palau',
 'Kazakhstan',
 'Russian Federation',
 'Belarus',
 'Turkey',
 'Uruguay',
 'Bulgaria',
 'Panama',
 'Bahamas',
 'Barbados',
 'Oman',
 'Georgia',
 'Costa Rica',
 'Malaysia',
 'Kuwait',
 'Serbia',
 'Mauritius',
 'Seychelles',
 'Trinidad and Tobago',
 'Albania',
 'Cuba',
 'Iran (Islamic Republic of)',
 'Sri Lanka',
 'Bosnia and Herzegovina',
 'Grenada',
 'Mexico',
 'Saint Kitts and Nevis',
 'Ukraine',
 'Antigua and Barbuda',
 'Peru',
 'Thailand',
 'Armenia',
 'North Macedonia',
 'Colombia',
 'Brazil',
 'China',
 'Ecuador',
 'Saint Lucia',
 'Azerbaijan',
 'Dominican Republic',
 'Moldova (Republic of)',
 'Algeria',
 'Lebanon',
 'Fiji',
 'Dominica',
 'Maldives',
 'Tunisia',
 'Saint Vincent and the Grenadines',
 'Suriname',
 'Mongolia',
 'Botswana',
 'Jamaica',
 'Jordan',
 'Paraguay',
 'Tonga',
 'Libya',
 'Uzbekistan',
 'Bolivia (Plurinational State of)',
 'Indonesia',
 'Philippines',
 'Belize',
 'Samoa',
 'Turkmenistan',
 'Venezuela (Bolivarian Republic of)

In [16]:
list(df_full_hdi[df_full_hdi['Inequality']==2].index.values)

['Bahrain',
 'Turkey',
 'Uruguay',
 'Panama',
 'Bahamas',
 'Barbados',
 'Costa Rica',
 'Kuwait',
 'Trinidad and Tobago',
 'Iran (Islamic Republic of)',
 'Sri Lanka',
 'Grenada',
 'Mexico',
 'Saint Kitts and Nevis',
 'Antigua and Barbuda',
 'Peru',
 'Thailand',
 'Colombia',
 'Brazil',
 'China',
 'Ecuador',
 'Saint Lucia',
 'Dominican Republic',
 'Algeria',
 'Fiji',
 'Dominica',
 'Maldives',
 'Tunisia',
 'Saint Vincent and the Grenadines',
 'Suriname',
 'Jamaica',
 'Jordan',
 'Paraguay',
 'Uzbekistan',
 'Bolivia (Plurinational State of)',
 'Indonesia',
 'Philippines',
 'Belize',
 'Turkmenistan',
 'Venezuela (Bolivarian Republic of)',
 'South Africa',
 'Palestine, State of',
 'Egypt',
 'Marshall Islands',
 'Viet Nam',
 'Gabon',
 'Morocco',
 'Guyana',
 'Iraq',
 'El Salvador',
 'Cabo Verde',
 'Guatemala',
 'Nicaragua',
 'Bhutan',
 'India',
 'Honduras',
 'Bangladesh',
 'Kiribati',
 'Sao Tome and Principe',
 'Micronesia (Federated States of)',
 "Lao People's Democratic Republic",
 'Eswatini (

In [17]:
list(df_full_hdi[df_full_hdi['Gender']==0].index.values)

['Hong Kong, China (SAR)',
 'Liechtenstein',
 'Malta',
 'Slovakia',
 'Hungary',
 'Saudi Arabia',
 'Bahrain',
 'Chile',
 'Qatar',
 'Brunei Darussalam',
 'Romania',
 'Palau',
 'Kazakhstan',
 'Russian Federation',
 'Turkey',
 'Uruguay',
 'Oman',
 'Georgia',
 'Malaysia',
 'Kuwait',
 'Mauritius',
 'Iran (Islamic Republic of)',
 'Sri Lanka',
 'Bosnia and Herzegovina',
 'Saint Kitts and Nevis',
 'Ukraine',
 'Thailand',
 'Brazil',
 'Fiji',
 'Maldives',
 'Saint Vincent and the Grenadines',
 'Mongolia',
 'Botswana',
 'Jamaica',
 'Tonga',
 'Libya',
 'Belize',
 'Samoa',
 'Venezuela (Bolivarian Republic of)',
 'Marshall Islands',
 'India',
 'Kiribati',
 'Micronesia (Federated States of)',
 'Vanuatu',
 'Kenya',
 'Solomon Islands',
 'Papua New Guinea']

In [18]:
list(df_full_hdi[df_full_hdi['Population']==1].index.values)

['Israel',
 'United Arab Emirates',
 'Saudi Arabia',
 'Bahrain',
 'Qatar',
 'Argentina',
 'Brunei Darussalam',
 'Palau',
 'Kazakhstan',
 'Turkey',
 'Panama',
 'Bahamas',
 'Oman',
 'Costa Rica',
 'Malaysia',
 'Iran (Islamic Republic of)',
 'Mexico',
 'Peru',
 'Colombia',
 'Brazil',
 'Ecuador',
 'Dominican Republic',
 'Algeria',
 'Lebanon',
 'Fiji',
 'Dominica',
 'Tunisia',
 'Suriname',
 'Mongolia',
 'Botswana',
 'Jamaica',
 'Jordan',
 'Paraguay',
 'Libya',
 'Uzbekistan',
 'Bolivia (Plurinational State of)',
 'Indonesia',
 'Turkmenistan',
 'Venezuela (Bolivarian Republic of)',
 'South Africa',
 'Palestine, State of',
 'Marshall Islands',
 'Gabon',
 'Morocco',
 'Iraq',
 'El Salvador',
 'Cabo Verde',
 'Nicaragua',
 'Honduras',
 'Sao Tome and Principe',
 'Equatorial Guinea',
 'Angola',
 'Congo',
 'Syrian Arab Republic',
 'Djibouti',
 'Haiti']

In [19]:
list(df_full_hdi[df_full_hdi['Expenditure']==2].index.values)

['Norway',
 'Iceland',
 'Australia',
 'Netherlands',
 'United Kingdom',
 'New Zealand',
 'Canada',
 'Liechtenstein',
 'Slovenia',
 'Spain',
 'France',
 'Czechia',
 'Italy',
 'Andorra',
 'Portugal',
 'Palau',
 'Cuba',
 'Brazil',
 'Marshall Islands',
 'Kiribati',
 'Micronesia (Federated States of)',
 'Afghanistan',
 'Sierra Leone']

In [20]:
list(df_full_hdi[df_full_hdi['Health']==0].index.values)

['Norway',
 'Ireland',
 'Hong Kong, China (SAR)',
 'Singapore',
 'United Kingdom',
 'Canada',
 'United States',
 'Slovenia',
 'Luxembourg',
 'Malta',
 'United Arab Emirates',
 'Cyprus',
 'Saudi Arabia',
 'Chile',
 'Qatar',
 'Brunei Darussalam',
 'Montenegro',
 'Palau',
 'Turkey',
 'Panama',
 'Bahamas',
 'Oman',
 'Costa Rica',
 'Malaysia',
 'Kuwait',
 'Mauritius',
 'Seychelles',
 'Albania',
 'Iran (Islamic Republic of)',
 'Sri Lanka',
 'Bosnia and Herzegovina',
 'Grenada',
 'Mexico',
 'Saint Kitts and Nevis',
 'Antigua and Barbuda',
 'North Macedonia',
 'Colombia',
 'Brazil',
 'China',
 'Ecuador',
 'Dominican Republic',
 'Algeria',
 'Lebanon',
 'Tunisia',
 'Saint Vincent and the Grenadines',
 'Suriname',
 'Jordan',
 'Libya',
 'Uzbekistan',
 'Turkmenistan',
 'Venezuela (Bolivarian Republic of)',
 'Palestine, State of',
 'Kyrgyzstan',
 'Tajikistan',
 'Timor-Leste']

In [22]:
list(df_full_hdi[df_full_hdi['Environment']==0].index.values)

['Sweden',
 'Finland',
 'Austria',
 'Japan',
 'Slovenia',
 'Korea (Republic of)',
 'Latvia',
 'Brunei Darussalam',
 'Montenegro',
 'Palau',
 'Panama',
 'Costa Rica',
 'Malaysia',
 'Seychelles',
 'Peru',
 'Brazil',
 'Saint Vincent and the Grenadines',
 'Suriname',
 'Bolivia (Plurinational State of)',
 'Belize',
 'Samoa',
 'Venezuela (Bolivarian Republic of)',
 'Marshall Islands',
 'Gabon',
 'Guyana',
 'Bhutan',
 'Sao Tome and Principe',
 'Micronesia (Federated States of)',
 "Lao People's Democratic Republic",
 'Equatorial Guinea',
 'Zambia',
 'Congo',
 'Solomon Islands',
 'Papua New Guinea',
 'Congo (Democratic Republic of the)',
 'Guinea-Bissau']

In [ ]:
### pd.DataFrame(df_full_hdi).to_csv("teste_cluster_results_hdi.csv", index=False) ###