In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
from sklearn.neighbors import NearestNeighbors

%matplotlib inline 

In [2]:
### Importing all the dataframes with only the Cluster that Brazil is located in each case ###
df_economy_hdi = pd.read_csv('df_economy_hdi.csv')
df_inequality_hdi = pd.read_csv('df_inequality_hdi.csv')
df_gender_hdi = pd.read_csv('df_gender_hdi.csv')
df_population_hdi = pd.read_csv('df_population_hdi.csv')
df_expenditure_hdi = pd.read_csv('df_expenditure_hdi.csv') 
df_health_hdi = pd.read_csv('df_health_hdi.csv') 
df_environment_hdi = pd.read_csv('df_environment_hdi.csv') 

In [3]:
### Locating and showing the position of Brazil in each dataframe!!! ###
economy_bra = df_economy_hdi[df_economy_hdi['Country']=='Brazil']
display(economy_bra)
inequality_bra = df_inequality_hdi[df_inequality_hdi['Country']=='Brazil']
display(inequality_bra)
gender_bra = df_gender_hdi[df_gender_hdi['Country']=='Brazil']
display(gender_bra)
population_bra = df_population_hdi[df_population_hdi['Country']=='Brazil']
display(population_bra)
expenditure_bra = df_expenditure_hdi[df_expenditure_hdi['Country']=='Brazil']
display(expenditure_bra)
health_bra = df_health_hdi[df_health_hdi['Country']=='Brazil']
display(health_bra)
environment_bra = df_environment_hdi[df_environment_hdi['Country']=='Brazil']
display(environment_bra)

Country      HDI        LE       EYS       MYS       GNI  Economy
36  Brazil  0.65897  0.715643  0.614119  0.506661  0.103694        2

Country      IHDI       ILE        IE        II        VE  RPAE       SLF  \
18  Brazil  0.506747  0.220779  0.414555  0.669368  0.293995   1.0  0.648593   

    Inequality  
18           2

Country      GDIV      GIIV       SSP      WAFI  Gender
27  Brazil  0.922445  0.497403  0.269189  0.669624       0

Country        TP       TUP        MA  Population
19  Brazil  0.147187  0.847926  0.551992           1

Country       CHE       GEE      RDE  Expenditure
17  Brazil  0.521803  0.458251  0.25292            2

Country       PPP        HB  Health
37  Brazil  0.255751  0.154503       0

Country      CDEP       CDE       FA       FAC       DMC       RLI  \
15  Brazil  0.056879  0.150589  0.59976  0.226697  0.319205  0.840719   

    Environment  
15            0

In [4]:
### Saving just the Brazil's index for each case! ###
economy = 36
inequality = 18
gender = 27
population = 19
expenditure = 17
health = 37
environment = 15

In [5]:
### Changing the index to make the numpy array only with float!! ###
df_economy_hdi.set_index('Country',inplace=True)
df_inequality_hdi.set_index('Country',inplace=True)
df_gender_hdi.set_index('Country',inplace=True)
df_population_hdi.set_index('Country',inplace=True)
df_expenditure_hdi.set_index('Country',inplace=True)
df_health_hdi.set_index('Country',inplace=True)
df_environment_hdi.set_index('Country',inplace=True)

In [6]:
### Loading the data into a NumPy array ###
economy_hdi = np.array(df_economy_hdi)
inequality_hdi = np.array(df_inequality_hdi)
gender_hdi = np.array(df_gender_hdi)
population_hdi = np.array(df_population_hdi)
expenditure_hdi = np.array(df_expenditure_hdi)
health_hdi = np.array(df_health_hdi)
environment_hdi = np.array(df_environment_hdi)

#display(economy_hdi)

In [7]:
### Fiting the NearestNeighbors objects ###

knn = NearestNeighbors(n_neighbors=5).fit(economy_hdi)
distances, indices = knn.kneighbors(economy_hdi)

economy = indices[36]
economy

array([36, 32, 43, 35, 48], dtype=int64)

In [8]:
inequality_knn = knn.fit(inequality_hdi)
distances, indices = knn.kneighbors(inequality_hdi)

inequality = indices[18]
inequality

array([18, 17, 37,  8,  3], dtype=int64)

In [9]:
gender_knn = knn.fit(gender_hdi)
distances, indices = knn.kneighbors(gender_hdi)

gender = indices[27]
gender

array([27, 17, 33, 26, 24], dtype=int64)

In [10]:
population_knn = knn.fit(population_hdi)
distances, indices = knn.kneighbors(population_hdi)

population = indices[19]
population

array([19,  2,  1,  5, 18], dtype=int64)

In [11]:
expenditure_knn = knn.fit(expenditure_hdi)
distances, indices = knn.kneighbors(expenditure_hdi)

expenditure = indices[17]
expenditure

array([17,  5, 19,  4, 14], dtype=int64)

In [12]:
health_knn = knn.fit(health_hdi)
distances, indices = knn.kneighbors(health_hdi)

health = indices[37]
health

array([37, 36,  3, 42, 13], dtype=int64)

In [13]:
environment_knn = knn.fit(environment_hdi)
distances, indices = knn.kneighbors(environment_hdi)

environment = indices[15]
environment

array([15, 29, 19,  6,  4], dtype=int64)

In [14]:
### Making sure that the inde it's not tehe Country, to find the Countrys using the index number!!!
df_economy_hdi = pd.read_csv('df_economy_hdi.csv')
df_inequality_hdi = pd.read_csv('df_inequality_hdi.csv')
df_gender_hdi = pd.read_csv('df_gender_hdi.csv')
df_population_hdi = pd.read_csv('df_population_hdi.csv')
df_expenditure_hdi = pd.read_csv('df_expenditure_hdi.csv') 
df_health_hdi = pd.read_csv('df_health_hdi.csv') 
df_environment_hdi = pd.read_csv('df_environment_hdi.csv') 

In [15]:
df_economy_hdi.loc[economy]['Country']

36      Brazil
32    Thailand
43     Algeria
35    Colombia
48     Tunisia
Name: Country, dtype: object

In [16]:
df_inequality_hdi.loc[inequality]['Country']

18                 Brazil
17               Colombia
37                 Belize
8     Trinidad and Tobago
3                  Panama
Name: Country, dtype: object

In [17]:
df_gender_hdi.loc[gender]['Country']

27                   Brazil
17                  Georgia
33                  Jamaica
26                 Thailand
24    Saint Kitts and Nevis
Name: Country, dtype: object

In [18]:
df_population_hdi.loc[population]['Country']

19                  Brazil
2             Saudi Arabia
1     United Arab Emirates
5                Argentina
18                Colombia
Name: Country, dtype: object

In [19]:
df_expenditure_hdi.loc[expenditure]['Country']

17            Brazil
5        New Zealand
19          Kiribati
4     United Kingdom
14          Portugal
Name: Country, dtype: object

In [20]:
df_health_hdi.loc[health]['Country']

37       Brazil
36     Colombia
3     Singapore
42      Lebanon
13        Chile
Name: Country, dtype: object

In [21]:
df_environment_hdi.loc[environment]['Country']

15               Brazil
29    Equatorial Guinea
19               Belize
6                Latvia
4              Slovenia
Name: Country, dtype: object

In [22]:
## Using all columns to find the 5 Countrys closer to Brazil ###
df_scaler = pd.read_csv('df_scaler.csv')
df_country = pd.read_excel('dados_hdi.xlsx')
df_country = df_country[['Country']]
df_scaler = pd.concat([df_country,df_scaler],axis=1)

brazil = df_scaler[df_scaler['Country']=='Brazil']
display(brazil)

Country      HDI        LE       EYS       MYS       GNI      GDIV  \
83  Brazil  0.65897  0.715643  0.614119  0.506661  0.103694  0.922445   

        GIIV      IHDI       ILE  ...  RPAE      WAFI      CDEP       CDE  \
83  0.497403  0.506747  0.220779  ...   1.0  0.669624  0.056879  0.150589   

         FA       FAC       DMC       RLI       SLF      RDE  
83  0.59976  0.226697  0.319205  0.840719  0.648593  0.25292  

[1 rows x 31 columns]

In [23]:
df_scaler.set_index('Country',inplace=True)
scaler_hdi = np.array(df_scaler)

In [24]:
knn = NearestNeighbors(n_neighbors=5).fit(scaler_hdi)
distances, indices = knn.kneighbors(scaler_hdi)

knn_brazil = indices[83]
knn_brazil

array([ 83,  82,  56, 102, 109], dtype=int64)

In [25]:
df_scaler = pd.read_csv('df_scaler.csv')
df_scaler = pd.concat([df_country,df_scaler],axis=1)

df_scaler.loc[knn_brazil]['Country']

83       Brazil
82     Colombia
56       Panama
102    Paraguay
109      Belize
Name: Country, dtype: object